Project/config/routes.rb
Rails.application.routes.draw do
  get '/' => "decisions#index", as: 'root'
  get '/category/:category' => "decisions#index_by_category", as: 'category'
  get '/home' => "decisions#home", as: 'home'
  
  get '/decision/:id/vote_1' => 'decisions#vote1', as: 'vote'
  get '/decision/:id/vote_2' => 'decisions#vote2', as: 'vote2'
  get 'signup'  => 'users#new' 
  
  resources :users do
    resources :decisions
  end

  get 'login'=> 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

Project/app/models/decision.rb
class Decision < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image_1, ImageUploader
	mount_uploader :image_2, ImageUploader
	serialize :array_users, Array
	def self.last_created_decisions n
		Decision.order(created_at: :desc).limit(n)
	end
	def self.filter_by_category category
		 Decision.where("category is ?",category)
	end

	def self.more_voted_decisions n
		Decision.order(vote_1: :desc).limit(n)
	end
	
end

Project/app/models/user.rb
class User < ActiveRecord::Base
	has_many :decisions
	has_secure_password

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 	validates :email, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }
 	
 	mount_uploader :avatar, ImageUploader
 	mount_uploader :fondo, ImageUploader

end

Project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  protect_from_forgery with: :exception
		helper_method :current_user 

	def current_user 
  		@current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end
	def require_user 
  		redirect_to '/login' unless current_user 
	end

end

Project/app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
	before_action :require_user, only: [:new, :vote1, :vote2]
	def index
		@decisions = Decision.all
		@randomdecision = @decisions.sample
		@media1 = (@randomdecision.vote_1*100/(@randomdecision.vote_1+@randomdecision.vote_2).to_f).round
		@media2 = (@randomdecision.vote_2*100/(@randomdecision.vote_1+@randomdecision.vote_2).to_f).round
		@category = nil
	end
	def home
		@decisions = Decision.all
	end
	def new
		@user = User.find params[:user_id]
		@decision = Decision.new 
	end
	def  show
		@decision = Decision.find params[:id]
		@media2 = (@decision.vote_2*100/(@decision.vote_1+@decision.vote_2).to_f).round
		@media1 = (@decision.vote_1*100/(@decision.vote_1+@decision.vote_2).to_f).round

	end

	def index_by_category
		@decisions = Decision.all
		@decisions = Decision.filter_by_category params[:category]
		@randomdecision = @decisions.sample
		flash[:category] = params[:category]
		render 'index'
	end

	def last_decisions
		@last_decisions = Decision.last_created_decisions(5)
	end
	def more_voted
		@more_voted = Decision.more_voted_decisions(5)
	end

	def create
		@user = User.find params[:user_id]
		@decisions = @user.decisions.new decision_params
		if @decisions.save
			redirect_to user_path(current_user)
		else
			render 'new'
		end
	end
	
	def vote1
		@decision = Decision.find params[:id]
		@decision.vote_1 += 1
		@decision.array_users.push(current_user.id)
		if 	@decision.save
			if flash[:category] == nil
				redirect_to root_path
			else
				redirect_to category_path flash[:category]
			end
		end
	end
	
	def vote2
		@decision = Decision.find params[:id]
		@decision.vote_2 += 1
		@decision.array_users.push(current_user.id)
		if @decision.save
			flash[:category] == nil
			redirect_to root_path
		else
			redirect_to category_path flash[:category]
		end
	end
	def edit
		@decision = Decision.find params[:id]
		@user = User.find params[:user_id]
	end
	def update
		@decision = Decision.find params[:id]

		if @decision.update decision_params
			redirect_to @decision
		else
			render 'edit'
		end

	end

	def destroy
		@decision = Decision.find params[:id]
		@decision.destroy
		redirect_to  user_path(current_user)
	end
	
	private
	def decision_params
		params.require(:decision).permit(:category, :description, :name_1, :vote_1,:vote_2,:image_1,:name_2,:vote_2,:image_2,:date, :array_users)
	end
end

Project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new 
	end
	def create
    @user = User.find_by_email(params[:session][:email])
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to '/'
      else
      redirect_to 'login'
      end 
  end
  def destroy 
    session[:user_id] = nil 
    redirect_to '/' 
  end
end

Project/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
  	@user = User.new
	end
	def create 
  		@user = User.new(user_params) 
  		if @user.save 
    		session[:user_id] = @user.id 
    		redirect_to '/' 
  		else 
    		redirect_to '/signup' 
  		end 
	end

  def show
      @user = User.find params[:id]
      @decisions = @user.decisions.order(created_at: :desc)
  end
	
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar, :fondo)
  end
end

Project/app/helpers/application_helper.rb
module ApplicationHelper
end

Project/app/helpers/decisions_helper.rb
module DecisionsHelper
end

Project/app/helpers/products_helper.rb
module ProductsHelper
end

Project/app/helpers/rails_helper.rb
module RailsHelper
end

Project/app/helpers/sessions_helper.rb
module SessionsHelper
end

Project/app/helpers/users_helper.rb
module UsersHelper
end

Project/app/views/decisions/_form.html.erb
<!--
<%= form_for @product, html: { :multipart: true } do |form| %>
  <%= form.file_field :image %>
<% end %>

<div class="field">
	<%=f.label :image %> <br>
	<%= f.file_field :image %>
</div>
<div class="field">
	<%=f.label :title %> <br>
	<%= f.text_field :title %>
</div>
<div class="actions">
	<%=f.submit %>
</div>
<% end %>
-->

Project/app/views/decisions/edit.html.erb
<%= form_for @decision.id, :html => {:multipart => true} do |f| %>
<div class="form1">
	<div class="row">
		<div class="col-md-4 col-sm-4">
		 <%= f.label :Primera_Opción%>
		 <%= f.text_field :name_1, autofocus: true, placeholder: 'Título del Objeto' %>
		</div>
		<div class="col-md-1 col-sm-1">
	   		<%= f.label :Imagen_1 %>
		</div>
		<div class="col-md-4 col-sm-4 newimg">
	 	<%= f.file_field :image_1 %>
	 	</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-sm-4">
	 	<%= f.label :Segunda_Opción %>
	 	<%= f.text_field :name_2, placeholder: 'Título del Objeto' %>
		</div>
		<div class="col-md-1 col-sm-1">
	   		<%= f.label :Imagen_2 %>
		</div>
		<div class="col-md-4 col-sm-4 newimg">
	 		<%= f.file_field :image_2 %>
	 	</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-sm-4">
	 		<br>
	 		<%= f.label :Categoría %>
	 		<%= f.select :category,  options_for_select([ "Música", "Libros","Informática", "Móviles"], "Música") %>
		</div>
		<div class="col-md-4 col-sm-4">
			<%= f.label :Descripción %>
			<%= f.text_area :description %>
		</div>
	</div>
		<br>
	 <%= f.label :disponible_hasta %>
	 <%= f.date_field :date %>
	 <span class="btn-decision">
	 <%= f.submit 'Enviar', class: "btn-submit" %>
	</span>
	 <% end %>


</div>
	</div>

Project/app/views/decisions/home.html.erb
<div class="row">
	<% @decisions.each do |decision| %>
		<% decision.vote_1 + decision.vote_2 %>
	<% end %>

	<div class="col-md-3 col-sm-3" id="show">
		<div id="titles">
		 Decisiones más votadas
		</div>
		<hr>
		<% @decisions.more_voted_decisions(5).each do |decision| %>
			<li id="lista"><%= decision.name_1 %> Vs <%= decision.name_2 %> <%= link_to 'Mostrar', user_decision_path(decision.user_id, decision)%> </li>
		<% end %>
	</div>
	<div class="col-md-3 col-sm-3" id="show">
		<div id="titles">
			Últimas Decisiones 
		</div>
		
		<hr>

		<% @decisions.limit(2).each do |decision| %>
			<li id="lista"><%= decision.name_1 %> Vs <%= decision.name_2 %> <%= link_to 'Mostrar', user_decision_path(decision.user_id,decision)%> </li>
		<% end %>
	</div>
		<div class="col-md-3 col-sm-3" id="show">
		<div id="titles">
			Decisiones Finalizadas
		</div>
		
		<hr>

		<% @decisions.each do |decision| %>
			<% if decision.date < DateTime.now %>
				<li id="lista"><%= decision.name_1 %> Vs <%= decision.name_2 %> <%= link_to 'Mostrar', user_decision_path(decision.user_id,decision)%> </li>
			<% end %>
		<% end %>
	</div>
</div>
<div class="row">
	<div class="col-md-3 col-sm-3" id="show">
		<div id="titles">
		 Categorias
		</div>
		<hr>
		<% @decisions.each do |decision| %>
			<li id="lista"><%= decision.category %><%= link_to 'Mostrar', category_path %></li>
		<% end %>
		</div>
	</div>
</div>

<!--
<div id="slider">
    <div>HOLA</div>
    <div>que tal</div>
    <div>bien</div>
</div>
<!--
<div id="slider">
    <div>HOLA</div>
    <div>que tal</div>
    <div>bien</div>
</div>
-->

Project/app/views/decisions/index.html.erb
    <div  id="efect" >
      <section id="contain">
        <div class="col-md-4 col-sm-4 option1">
           <p class="name1"><%= @randomdecision.name_1 %></p>
           <img  class="decisionimage" src="<%= @randomdecision.image_1_url.to_s %>">
          <p id="vote1">
            <%= @randomdecision.vote_1 %>
            <span id="vote1img">
              <% if @randomdecision.date > DateTime.now %>
                <% if current_user %>
                <% user_in_decision = @randomdecision.array_users.find{|id| id ==  current_user.id } %>
                <% end %>
                <% if user_in_decision.blank? %> 
                  <%= link_to 'Votar', vote_path(@randomdecision),:controller => :decisions, :action => :vote1, class: "btn btn-success"%>
                <% else %>
                 <span class="glyphicon glyphicon-remove"></span>
                <% end %>
            </span>
              <% else %>
                <span class="btn btn-success">Votación Finalizada</span>
              <% end %>
          </p>
        </div>
         <div class="col-md-4 col-sm-4 option3">
            <div class="category">
              Categoría : <%= link_to(@randomdecision.category, category_path(@randomdecision.category)) %>
            </div>
            <div class="date">
              Votación termina : <%= @randomdecision.date %>
            </div>
            <div class="progress">
    <div class="progress-bar progress-bar-success" style="width: <%= @media1 %>% ">
      <span class="sr-only"></span>
    </div>
    <div class="progress-bar progress-bar-info" style="width: <%= @media2 %>% ">
      <span class="sr-only"></span>
    </div>
      </div>
          </div>
     
    <div class="col-md-4 col-sm-4 option2">
        <p class="name2"><%= @randomdecision.name_2 %></p>
          <img  class="decisionimage" src="<%= @randomdecision.image_2_url.to_s %>">
        <p id="vote2">

          <%= @randomdecision.vote_2 %><span id="vote2img">
          <% if @randomdecision.date > DateTime.now %>
          <% if user_in_decision.blank? %>
          <%= link_to 'Votar', vote2_path(@randomdecision), :controller => :decisions, :action => :vote2, class: "btn btn-success"%>
           <% else %>
           <span class="glyphicon glyphicon-remove"></span>

           <% end %>
               <% else %>
                  <span class="btn btn-success">Votación Finalizada</span>
            <% end %>
        </span>
        </p>
    </div>
  <div class="col-md-12 col-sm-12">
    </div>
    <div class="col-md-12 col-sm-12 description">
            <p>
                <%= @randomdecision.description %>
           </p>
    </div>
  </section>

Project/app/views/decisions/new.html.erb
<%= form_for [@user,@decision], :html => {:multipart => true} do |f| %>
	<div class="form1">
		<div class="row">
			<div class="col-md-4 col-sm-4">
				<%= f.label :Primera_Opción%>
				<%= f.text_field :name_1, autofocus: true, placeholder: 'Título del Objeto' %>
			</div>
		<div class="col-md-1 col-sm-1">
	   		<%= f.label :Imagen_1 %>
		</div>
		<div class="col-md-4 col-sm-4 newimg">
	 	<%= f.file_field :image_1 %>
	 	</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-sm-4">
			 <%= f.label :Segunda_Opción %>
			 <%= f.text_field :name_2, placeholder: 'Título del Objeto' %>
		</div>
	 	<div class="col-md-1 col-sm-1">
	   		<%= f.label :Imagen_2 %>
		</div>
		<div class="col-md-4 col-sm-4 newimg">
	 	<%= f.file_field :image_2 %>
	 	</div>
	</div>
		<div class="row">
	 		<div class="col-md-4 col-sm-4">
	 	<br>
	 		<%= f.label :Categoría %>
	 		<%= f.select :category,  options_for_select([ "Música", "Libros","Informática", "Móviles","Viajes"], "Música") %>
			</div>
			<div class="col-md-4 col-sm-4">
				 <%= f.label :Descripción %>
				 <%= f.text_area :description %>
			</div>
		</div>
	<br>
	 <%= f.label :disponible_hasta %>
	 <%= f.date_field :date %>
	 <br>
	 <%= f.hidden_field :vote_1, :value => (10..40).to_a.sample %>
	 <%= f.hidden_field :vote_2, :value => (10..40).to_a.sample %>
	 <span class="btn-decision">
	 <%= f.submit 'Enviar', class: "btn-submit" %>
	</span>
	 <% end %>
</div>

Project/app/views/decisions/show.html.erb
     <div  id="efect" >
      <section id="contain">
        <div class="col-md-4 col-sm-4 option1">
           <p class="name1"><%= @decision.name_1 %></p>
           <img  class="decisionimage" src="<%= @decision.image_1_url.to_s %>">
          <p id="vote1">
            <%= @decision.vote_1 %>
            <span id="vote1img">
              <% if @decision.date > DateTime.now %>

                <% user_in_decision = @decision.array_users.find{|id| id ==  current_user.id } %>
                <% if user_in_decision.blank? %> 
                  <%= link_to 'Votar', vote_path(@decision),:controller => :decisions, :action => :vote1, class: "btn btn-success"%>
                <% else %>
                 <span class="glyphicon glyphicon-remove"></span>
                <% end %>
            </span>
              <% else %>
                <span class="btn btn-success">Votación Finalizada</span>
              <% end %>
          </p>
        </div>
         <div class="col-md-4 col-sm-4 option3">
            <div class="category">
              Categoría : <%= link_to(@decision.category, category_path(@decision.category)) %>
            </div>
            <div class="date">
              Votación termina : <%= @decision.date %>
            </div>
            <div class="progress">
    <div class="progress-bar progress-bar-success" style="width: <%= @media1 %>% ">
      <span class="sr-only"></span>
    </div>
    <div class="progress-bar progress-bar-info" style="width: <%= @media2 %>% ">
      <span class="sr-only"></span>
    </div>
      </div>
          </div>
     
    <div class="col-md-4 col-sm-4 option2">
        <p class="name2"><%= @decision.name_2 %></p>
          <img  class="decisionimage" src="<%= @decision.image_2_url.to_s %>">
        <p id="vote2">

          <%= @decision.vote_2 %><span id="vote2img">
          <% if @decision.date > DateTime.now %>
          <% if user_in_decision.blank? %>
          <%= link_to 'Votar', vote2_path(@decision), :controller => :decisions, :action => :vote2, class: "btn btn-success"%>
           <% else %>
           <span class="glyphicon glyphicon-remove"></span>

           <% end %>
               <% else %>
                  <span class="btn btn-success">Votación Finalizada</span>
            <% end %>
        </span>
        </p>
    </div>
 
  <div class="col-md-12 col-sm-12">
    

    </div>
    <div class="col-md-12 col-sm-12 description">
            <p>
                <%= @decision.description %>
           </p>
    </div>
  </section>

Project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application'%>
  <%= csrf_meta_tags %>

    <meta charset='utf-8'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400;300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link href='style.css' rel='stylesheet'>  
    
</head>

<body class="background">
  <div id='cssmenu'>
    <ul>
        <li><a><%= link_to 'Inicio',  root_path(@decision)%></a></li>
        <% if current_user %>
          <li><a><%= link_to 'Nueva Decisión',  new_user_decision_path(current_user.id, @decision)%></a></li>
        <%else %>
          <li><a><%= link_to 'Nueva Decisión',  'signup' %></a></li>
          <% end %>

        <% if current_user %> 
            <li><a><%= link_to "Log out", logout_path, method: "delete" %></a></li>
            <div class="email"><img id="avatar" src="<%= current_user.avatar_url.to_s %>"><%= link_to(current_user.email, user_path(current_user)) %></div>

        <% else %> 
            <li><a><%= link_to "Login", 'login' %></a></li> 
            <li><a><%= link_to "Registro", 'signup' %></a></li>

        <% end %>  
    </ul>
  </div>
<!--
<ul class="nav nav-pills">
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Categorías <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Informática", 'category/informática' %></li>
      <li><%= link_to "Libros", 'category/libros' %></li>
      <li><%= link_to "Música", 'category/musica' %></li>
    </ul>
  </li>
</ul>
-->
<%= yield %>
<%= javascript_include_tag 'application'%>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>

Project/app/views/rails/s.html.erb
<h1>Rails#s</h1>
<p>Find me in app/views/rails/s.html.erb</p>

Project/app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Registrarse</h1>

    <%= form_for @user, :html => {:multipart => true} do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.label :Elige_tu_foto_de_Perfil %>
      <%= f.file_field :avatar, :placeholder => "Enlace imagen Avatar" %>
      <%= f.label :Elige_tu_foto_de_Portada %>
      <%= f.file_field :fondo, :placeholder => "Enlace imagen fondo" %>
      <%= f.submit "Crear la cuenta", class: "btn-submit" %>
    <% end %>



  
    </div>
  </div>
</div>

Project/app/views/users/show.html.erb
<img class="fondo" src="<%= @user.fondo_url.to_s %>">
<div class="row">
	<div class="col-md-4 col-sm-4 user">
		<img id="userimg" src="<%= @user.avatar_url.to_s %>">
		<p>
		Usuario: <%= @user.first_name %> <%= @user.last_name %> 
		</p>
		<p>
		Email: <%= @user.email %> 
		</p>
	</div>


	<div class="col-md-3 col-sm-3" id="show">
		<div id="titles">
		 Tus decisiones
		</div>
		<hr>
		<% @decisions.each do |decision| %>
			<li id="lista"><%= decision.name_1 %> Vs <%= decision.name_2 %> <%= link_to '', user_decision_path(@user,decision), class: "glyphicon glyphicon-eye-open" %> 
				<%= link_to '', user_decision_path(@user,decision), method: :delete, data: { confirm: 'Vas a eliminar esta decisión' }, class: "glyphicon glyphicon-remove" %></li>

		<% end %>
	</div>

	<div class="col-md-3 col-sm-3" id="show">
		<div id="titles">
			Tus Últimas Decisiones 
		</div>
		
		<hr>

		<% @decisions.last_created_decisions(2).each do |decision| %>
			<li id="lista"><%= decision.name_1 %> Vs <%= decision.name_2 %> <%= link_to '', user_decision_path(@user,decision), class: "glyphicon glyphicon-eye-open"%>
			<%= link_to '', user_decision_path(@user,decision), method: :delete, data: { confirm: 'Vas a eliminar esta decisión' }, class: "glyphicon glyphicon-remove" %></li>
		<% end %>
	</div>
</div>